### ISSUE TITLE
820px is too narrow for global-nav container

### ISSUE THREAD

**Issue by kurtextrem** [sindresorhus/refined-twitter#86]
I get this layout: http://prntscr.com/ir3a1h

It's because of 
```css
.global-nav .container {
	max-width: 820px !important;
}
```

`920px` would work.

Resolution: `1920x1080`, in window: `1920x949`
